### ISSUE TITLE
How to show selected node ? 

### ISSUE THREAD

**Issue by DuongQuocHai** [mbaumgartenbr/flutter_tree_view#9]
How do I show the UI that the node I'm selecting? I see there is onTab function but it doesn't have this function.

**Comment by mbaumgartenbr** [comment]
Hey! Could you explain what are you trying to achieve?

There's no select/deselect functionality in the package, I've implemented it in the first version of the package but I found out that it would be better if the user could store and manipulate this kind of properties.

If you want select/deselect functionality, you should create your own `NodeWidget`. I made it super simple intentionally so you could create your own widget and add properties as you wish.

For example, instead of NodeWidget (I assume it's from it that you are asking about onTap) you could create a `ListTile` Widget and store somewhere the selected node and every time the user taps or long presses the `ListTile` you change the selected node.

I could make an example on how to work with select/deselect, enable/disable but I don't have much time in the next couple of days.

**Comment by DuongQuocHai** [comment]
Thank you for answering my question!

I found my answer here https://github.com/mbaumgartenbr/flutter_tree_view/issues/1 

I try to set the node.isSelected property to true, but in TreeNode there is no isSelected property.

hope you can do a small example here?

**Comment by DuongQuocHai** [comment]
Thank you very much!
It worked ^^ but the UI is no longer a treeview but I already have the basis to continue.

Good a night day ^^
